[package]
name = "localhost"
version = "0.1.0"
authors = ["Naughie <zomacchi@gmail.com>"]

[dependencies]
rocket = "0.4.0-rc.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["serve"]
